### ISSUE TITLE
Derive column properties from data

### ISSUE THREAD

**Issue by puehringer** [lineupjs/lineupjs#231] opened 2020-01-14 10:41 UTC
* Release number or git hash: v4.0.0-alpha.12
 * Web browser version and OS: any

### Steps to reproduce

 1. Use a Ranking without the builder

### Observed behavior
The column descriptions require data dependent entries (such as `categories` in `CategoricalColumn`, or `min/max` in `NumberColumn`). 

### Expected behavior
This existing description should be used if available, but if not it should be derived automatically from the data. This also includes making a setter for said properties such as `categories` to otherwise manually reload them after the data is loaded.

**Comment by thinkh** [comment] 2020-02-10 13:52
Duplicate of #236

**Closed by thinkh** 2020-02-10 13:52 UTC
Labels: lineup: v4, type: feature
